server:
  port: 8081

spring:
  datasource:
    dynamic:
      primary:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://127.0.0.1:3316/eq-multi-ds1?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&rewriteBatchedStatements=true
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
      ds2:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://127.0.0.1:3316/eq-multi-ds2?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&rewriteBatchedStatements=true
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver

easy-query:
  build: false